### PR TITLE
Enable CRB and EPEL if we are running with the EPEL profile

### PR DESCRIPTION
**Pull request by msrb**
Fixes: OSCI-6783

### CODE REVIEW

**Comment by msrb** [comment]
It seems like epel

https://artifacts.dev.testing-farm.io/7d43c63c-ac23-454d-9c43-8382d9fdf002/

```
+ [[ centos-stream-9 == centos-stream-* ]]
+ echo 'Enabling CRB and EPEL...'
Enabling CRB and EPEL...
+ yum config-manager --enable crb
+ yum -y install epel-release
CentOS Stream 9 - BaseOS                         59 kB/s | 2.3 kB     00:00    
CentOS Stream 9 - BaseOS - Debug                114 kB/s | 1.5 kB     00:00    
CentOS Stream 9 - BaseOS - Source               108 kB/s | 1.5 kB     00:00    
CentOS Stream 9 - AppStream                     206 kB/s | 2.8 kB     00:00    
CentOS Stream 9 - AppStream - Debug             120 kB/s | 1.5 kB     00:00    
CentOS Stream 9 - AppStream - Source             97 kB/s | 1.5 kB     00:00    
CentOS Stream 9 - CRB                           205 kB/s | 2.7 kB     00:00    
CentOS Stream 9 - CRB - Debug                   127 kB/s | 1.5 kB     00:00    
CentOS Stream 9 - CRB - Source                  105 kB/s | 1.5 kB     00:00    
CentOS Stream 9 - HighAvailability              176 kB/s | 2.3 kB     00:00    
CentOS Stream 9 - HighAvailability - Debug      110 kB/s | 1.5 kB     00:00    
CentOS Stream 9 - HighAvailability - Source     107 kB/s | 1.5 kB     00:00    
CentOS Stream 9 - NFV                           162 kB/s | 2.3 kB     00:00    
CentOS Stream 9 - NFV - Debug                   116 kB/s | 1.5 kB     00:00    
CentOS Stream 9 - NFV - Source                  107 kB/s | 1.5 kB     00:00    
CentOS Stream 9 - RT                            211 kB/s | 2.3 kB     00:00    
CentOS Stream 9 - RT - Debug                    103 kB/s | 1.5 kB     00:00    
CentOS Stream 9 - RT - Source                   106 kB/s | 1.5 kB     00:00    
CentOS Stream 9 - ResilientStorage              154 kB/s | 2.3 kB     00:00    
CentOS Stream 9 - ResilientStorage - Debug      122 kB/s | 1.5 kB     00:00    
CentOS Stream 9 - ResilientStorage - Source     115 kB/s | 1.5 kB     00:00    
CentOS Stream 9 - SAP                            70 kB/s | 2.3 kB     00:00    
CentOS Stream 9 - SAP - Debug                   101 kB/s | 1.5 kB     00:00    
CentOS Stream 9 - SAP - Source                  102 kB/s | 1.5 kB     00:00    
CentOS Stream 9 - SAPHANA                       163 kB/s | 2.3 kB     00:00    
CentOS Stream 9 - SAPHANA - Debug               110 kB/s | 1.5 kB     00:00    
CentOS Stream 9 - SAPHANA - Source              128 kB/s | 1.5 kB     00:00    
CentOS Stream 9 Buildroot                       3.1 kB/s | 3.8 kB     00:01    
Package epel-release-9-7.el9.noarch is already installed.
Dependencies resolved.
Nothing to do.
Complete!
```

**Comment by psss** [comment]
Hm, interesting. For reference, here's a recent pull request and Testing Farm job which failed:

* https://src.fedoraproject.org/rpms/tmt/pull-request/159
* https://artifacts.dev.testing-farm.io/05ee52fd-87bc-4cdb-9819-1757af2abb90/

**Comment by psss** [comment]
The installability job complains about missing `python3.9dist(typing-extensions)`, but they are in `epel9`:

```
# dnf install -y 'python3.9dist(typing-extensions) >= 4.9'
Extra Packages for Enterprise Linux 9 - x86_64                 11 MB/s |  23 MB     00:02    
Extra Packages for Enterprise Linux 9 openh264 (From Cisco) - 7.6 kB/s | 2.5 kB     00:00    
Extra Packages for Enterprise Linux 9 - Next - x86_64         995 kB/s | 276 kB     00:00    
Dependencies resolved.
==============================================================================================
 Package                            Architecture    Version               Repository     Size
==============================================================================================
Installing:
 python3-typing-extensions          noarch          4.12.2-2.el9          epel           74 k

Transaction Summary
==============================================================================================
Install  1 Package
```

**Comment by msrb** [comment]
Could this be TF adding/enabling the EPEL repository automatically? And possibly using some older version or something (?)

**Comment by msrb** [comment]
Ah, I think I understand now. I think `epel-release` is pre-installed by TF, but the repo is actually disabled...

Let's see...

**Comment by msrb** [comment]
Meh...

```
Package epel-release-9-7.el9.noarch is already installed.
Dependencies resolved.
Nothing to do.
Complete!
+ yum config-manager --enable epel
Error: No matching repo to modify: epel.
```

So something is installing `epel-release`, but then probably monkey-patching the system and modifying the repos :thinking:

**Comment by psss** [comment]
@thrix, @happz, is Testing Farm possibly doing any changes to the epel repo files?

**Comment by thrix** [comment]
I am looking at this

**Comment by thrix** [comment]
@msrb not really, it should be installed and enabled (we do not disable it as in RHEL)

**Comment by martinhoyer** [comment]
Using the reproducer from https://artifacts.dev.testing-farm.io/7d43c63c-ac23-454d-9c43-8382d9fdf002/ the `epel` and `crb` repos are present, but not enabled.  
`dnf install tmt --enablerepo=epel --enablerepo=crb` works as expected.

**Comment by thrix** [comment]
@msrb I do not see a problem with Testing Farm, has to be installability, most probably `mtps-prepare-system`

**Comment by psss** [comment]
Here's a fresh instance of the problem:

* https://artifacts.dev.testing-farm.io/87bfb10f-ca54-466b-9aa0-42cfb01bd00f/

@msrb, are you familiar with `mtps-prepare-system`? Who does currently take care of it?

**Comment by thrix** [comment]
@msrb FTR, this is the state after TF hands over the execution to tmt:

```
❯ testing-farm reserve --compose CentOS-Stream-9
💻 CentOS-Stream-9 on x86_64 
🕗 Reserved for 30 minutes
⏳ Maximum reservation time is 720 minutes
🔎 https://api.dev.testing-farm.io/v0.1/requests/c7726e59-f761-43e9-b0cf-bd42a7dccfca
🔑 Adding SSH proxy key
Identity added: (stdin) (proxy@ip-172-31-22-4.us-east-2.compute.internal)
🌎 ssh -J proxy@testing-farm.io root@18.222.215.129
Welcome to Testing Farm!

Machine is reserved for 30 minutes.

To extend the reservation, run 'extend-reservation MINUTES'.

To return machine back, run 'return2testingfarm'.

To reboot the machine, use 'tmt-reboot'.
Last login: Tue Oct 29 10:43:06 2024 from 18.191.202.183


[root@ip-172-31-28-98 ~]# rpm -q epel-release
epel-release-9-7.el9.noarch

[root@ip-172-31-28-98 ~]# dnf makecache
Tag repository for c9s-build                                                                                                                                                                                  22 MB/s |  14 MB     00:00    
Copr repo for beakerlib-beakerlib-master owned by packit                                                                                                                                                      35 kB/s | 1.8 kB     00:00    
CentOS Stream 9 - BaseOS                                                                                                                                                                                      35 kB/s | 5.0 kB     00:00    
CentOS Stream 9 - AppStream                                                                                                                                                                                   47 kB/s | 5.0 kB     00:00    
CentOS Stream 9 - CRB                                                                                                                                                                                         46 kB/s | 5.2 kB     00:00    
CentOS Stream 9 - Extras packages                                                                                                                                                                             73 kB/s | 6.9 kB     00:00    
Extra Packages for Enterprise Linux 9 - x86_64                                                                                                                                                               230 kB/s |  27 kB     00:00    
Extra Packages for Enterprise Linux 9 openh264 (From Cisco) - x86_64                                                                                                                                         5.7 kB/s | 993  B     00:00    
Extra Packages for Enterprise Linux 9 - Next - x86_64                                                                                                                                                        125 kB/s |  25 kB     00:00    
Metadata cache created.
```

As you can see, epel is enabled on the machines.

**Comment by psss** [comment]
Another instance of a failed job:

* https://src.fedoraproject.org/rpms/fmf/pull-request/18

@msrb, do you see anything wrong on the Testing Farm side from the output @thrix provided above?

**Comment by msrb** [comment]
@psss Nope, this is definitely mini-tps/pipeline issue.

**Comment by carlwgeorge** [comment]
Has an issue for this been filed anywhere else?  I believe I ran into the same problem today.

https://src.fedoraproject.org/rpms/python-jupyter-core/pull-request/21

**Pull request closed without merging**
