### PR TITLE
Switch to the official OSCI COPR

### PR DESCRIPTION
**Pull request by msrb**

### CODE REVIEW

**Comment by msrb** [comment]
Tested here: https://osci-jenkins-1.ci.fedoraproject.org/job/fedora-ci/job/installability-pipeline/view/change-requests/job/PR-22/

**Comment by msrb** [comment]
@Andrei-Stepanov PTAL -- moving away from the fork the proper upstream.

**Review by Andrei-Stepanov — APPROVED** [review]

**Comment by Andrei-Stepanov** [comment]
@msrb approved

**Comment by Andrei-Stepanov** [comment]
https://copr.fedorainfracloud.org/coprs/g/osci/mini-tps/build/6225155/

**Pull request merged**
